version: "3"

services: 
  es01: 
    image: elasticsearch:7.5.0
    container_name: es01
    environment: 
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - path.repo=/opt/elasticsearch/backup
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./backup:/opt/elasticsearch/backup
    networks:
      - es

  kibana:
    container_name: kibana
    image: kibana:7.5.0
    ports:
      - 5601:5601
    networks:
      - es  
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200

networks:
  es:
    driver: bridge
